# Generated by Django 3.2 on 2021-04-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videodata',
            name='datetimestamp',
        ),
        migrations.RemoveField(
            model_name='videodata',
            name='videoID',
        ),
        migrations.AddField(
            model_name='videodata',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
