# Generated by Django 3.2 on 2021-04-16 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_api', '0002_testmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testmodel',
            old_name='test',
            new_name='name',
        ),
    ]
