# Generated by Django 3.2 on 2021-04-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_api', '0002_auto_20210417_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videodata',
            name='id',
        ),
        migrations.AddField(
            model_name='videodata',
            name='datetimestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='videodata',
            name='videoID',
            field=models.CharField(default=1, editable=False, max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
