# Generated by Django 3.2 on 2021-04-17 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_api', '0003_auto_20210417_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videodata',
            name='datetimestamp',
        ),
    ]
