# Generated by Django 3.2 on 2021-04-18 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_api', '0004_remove_videodata_datetimestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testModel',
        ),
    ]
